apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: static-site
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./apps/static-site
      sourceRef:
        kind: GitRepository
        name: qa-env
        namespace: flux-system
  values:
    image:
      repository: 2024dock/static-site
      tag: "1.0.0"
